-- Unified JackUI schema. One Postgres database replacing 14 separate SQLite
-- files, with real foreign keys across what used to be isolated stores.
--
-- Conventions:
--   * Auto PKs: BIGINT GENERATED ALWAYS AS IDENTITY (users uses BY DEFAULT so
--     the auth ETL can preserve original ids).
--   * 0/1 flag columns: SMALLINT (the Go stores keep int semantics; avoids the
--     BOOLEAN `WHERE x = 0` runtime trap). DEFAULT mirrors the SQLite default.
--   * Timestamps: TIMESTAMPTZ, DEFAULT now() where SQLite used CURRENT_TIMESTAMP.
--   * SQLite REAL -> DOUBLE PRECISION; SQLite INTEGER -> BIGINT.
--   * Every user-owned table FKs user_id -> users(id) ON DELETE CASCADE. The
--     anonymous sentinel (id 0, used when auth is disabled and for legacy
--     favorites/history rows) is seeded below so those FKs hold in both modes.
--   * Full-text search (results.fts tsvector + GIN) is added in a later
--     migration alongside the history store port (needs an IMMUTABLE unaccent
--     wrapper).

-- ---------------------------------------------------------------------------
-- Level 0: users (root) + anonymous sentinel
-- ---------------------------------------------------------------------------
CREATE TABLE users (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username       TEXT NOT NULL UNIQUE,
    password_hash  TEXT NOT NULL,
    role           TEXT NOT NULL DEFAULT 'user',
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    email          TEXT NOT NULL DEFAULT '',
    status         TEXT NOT NULL DEFAULT 'active',
    email_verified SMALLINT NOT NULL DEFAULT 1,
    totp_secret    TEXT NOT NULL DEFAULT '',
    totp_enabled   SMALLINT NOT NULL DEFAULT 0,
    ntfy_topic     TEXT NOT NULL DEFAULT ''
);

-- Anonymous/sentinel user (id 0): satisfies user_id FKs when auth is disabled
-- and for legacy favorites/history rows written with user_id 0.
INSERT INTO users (id, username, password_hash, role, status, email_verified)
VALUES (0, '', '', 'guest', 'disabled', 0);

-- ---------------------------------------------------------------------------
-- Level 1: auth child tables
-- ---------------------------------------------------------------------------
CREATE TABLE refresh_tokens (
    token_hash  TEXT PRIMARY KEY,
    user_id     BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    expires_at  TIMESTAMPTZ NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    remember_me SMALLINT NOT NULL DEFAULT 0,
    user_agent  TEXT NOT NULL DEFAULT '',
    ip          TEXT NOT NULL DEFAULT '',
    consumed_at TIMESTAMPTZ
);
CREATE INDEX idx_refresh_user ON refresh_tokens(user_id);
CREATE INDEX idx_refresh_exp ON refresh_tokens(expires_at);

CREATE TABLE auth_tokens (
    token_hash TEXT PRIMARY KEY,
    user_id    BIGINT REFERENCES users(id) ON DELETE CASCADE,
    purpose    TEXT NOT NULL,
    email      TEXT NOT NULL DEFAULT '',
    expires_at TIMESTAMPTZ NOT NULL,
    used_at    TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_authtok_exp ON auth_tokens(expires_at);

CREATE TABLE webauthn_credentials (
    cred_id    TEXT PRIMARY KEY,
    user_id    BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    data       TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_wacred_user ON webauthn_credentials(user_id);

CREATE TABLE mfa_backup_codes (
    code_hash  TEXT PRIMARY KEY,
    user_id    BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    used_at    TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_backupcode_user ON mfa_backup_codes(user_id);

-- ---------------------------------------------------------------------------
-- Level 1: user-owned content
-- ---------------------------------------------------------------------------
CREATE TABLE results (
    id           BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    query        TEXT NOT NULL,
    title        TEXT NOT NULL DEFAULT '',
    tracker      TEXT NOT NULL DEFAULT '',
    category     TEXT NOT NULL DEFAULT '',
    size         BIGINT NOT NULL DEFAULT 0,
    seeders      BIGINT NOT NULL DEFAULT 0,
    leechers     BIGINT NOT NULL DEFAULT 0,
    age          TEXT NOT NULL DEFAULT '',
    magnet_uri   TEXT NOT NULL DEFAULT '',
    link         TEXT NOT NULL DEFAULT '',
    info_hash    TEXT NOT NULL DEFAULT '',
    publish_date TEXT NOT NULL DEFAULT '',
    saved_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    user_id      BIGINT NOT NULL DEFAULT 0 REFERENCES users(id) ON DELETE CASCADE,
    incognito    SMALLINT NOT NULL DEFAULT 0
);
CREATE INDEX idx_results_query ON results(LOWER(query));
CREATE INDEX idx_results_info_hash ON results(info_hash);
CREATE INDEX idx_results_saved_at ON results(saved_at);
CREATE INDEX idx_results_user_id ON results(user_id);

CREATE TABLE library (
    id                 BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    user_id            BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    info_hash          TEXT NOT NULL,
    magnet             TEXT NOT NULL,
    name               TEXT NOT NULL,
    primary_file_index BIGINT NOT NULL DEFAULT 0,
    total_size         BIGINT NOT NULL DEFAULT 0,
    resume_seconds     DOUBLE PRECISION NOT NULL DEFAULT 0,
    duration_seconds   DOUBLE PRECISION NOT NULL DEFAULT 0,
    kind               TEXT NOT NULL DEFAULT '',
    last_played_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    added_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_file_index    BIGINT NOT NULL DEFAULT -1,
    incognito          SMALLINT NOT NULL DEFAULT 0,
    UNIQUE (user_id, info_hash)
);
CREATE INDEX idx_lib_user_played ON library(user_id, last_played_at DESC);
CREATE INDEX idx_lib_hash ON library(info_hash);

CREATE TABLE rec_dismissed (
    user_id      BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    kind         TEXT NOT NULL,
    tmdb_id      BIGINT NOT NULL,
    dismissed_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (user_id, kind, tmdb_id)
);

CREATE TABLE downloads (
    id               BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    user_id          BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    info_hash        TEXT NOT NULL,
    file_index       BIGINT NOT NULL,
    file_path        TEXT NOT NULL,
    file_size        BIGINT NOT NULL,
    name             TEXT NOT NULL,
    magnet           TEXT NOT NULL,
    tracker          TEXT NOT NULL DEFAULT '',
    category         TEXT NOT NULL DEFAULT '',
    status           TEXT NOT NULL DEFAULT 'queued',
    bytes_downloaded BIGINT NOT NULL DEFAULT 0,
    started_at       TIMESTAMPTZ,
    completed_at     TIMESTAMPTZ,
    error            TEXT NOT NULL DEFAULT '',
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    priority         TEXT NOT NULL DEFAULT 'normal',
    queued_since     TIMESTAMPTZ,
    stalls           BIGINT NOT NULL DEFAULT 0,
    active_magnet    TEXT NOT NULL DEFAULT '',
    source           TEXT NOT NULL DEFAULT '',
    dest_base        TEXT NOT NULL DEFAULT '',
    dest_subdir      TEXT NOT NULL DEFAULT '',
    completion_dest  TEXT NOT NULL DEFAULT '',
    UNIQUE (user_id, info_hash, file_index)
);
CREATE INDEX idx_dl_user ON downloads(user_id);
CREATE INDEX idx_dl_status ON downloads(status);

CREATE TABLE download_sources (
    id          BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    download_id BIGINT NOT NULL REFERENCES downloads(id) ON DELETE CASCADE,
    magnet      TEXT NOT NULL,
    info_hash   TEXT NOT NULL,
    title       TEXT NOT NULL DEFAULT '',
    tracker     TEXT NOT NULL DEFAULT '',
    seeders     BIGINT NOT NULL DEFAULT 0,
    size        BIGINT NOT NULL DEFAULT 0,
    status      TEXT NOT NULL DEFAULT 'candidate',
    tries       BIGINT NOT NULL DEFAULT 0,
    last_tried  TIMESTAMPTZ,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (download_id, info_hash)
);
CREATE INDEX idx_src_dl ON download_sources(download_id);

CREATE TABLE playlists (
    id          BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    user_id     BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    name        TEXT NOT NULL,
    description TEXT NOT NULL DEFAULT '',
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_pl_user ON playlists(user_id);

CREATE TABLE watchlists (
    id             BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    user_id        BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    query          TEXT NOT NULL,
    category       TEXT NOT NULL DEFAULT '',
    min_seeders    BIGINT NOT NULL DEFAULT 1,
    ntfy_topic     TEXT NOT NULL DEFAULT '',
    sched_kind     TEXT NOT NULL DEFAULT 'interval',
    sched_minutes  BIGINT NOT NULL DEFAULT 0,
    sched_weekday  BIGINT NOT NULL DEFAULT 0,
    sched_hour     BIGINT NOT NULL DEFAULT 0,
    sched_minute   BIGINT NOT NULL DEFAULT 0,
    next_check_at  TIMESTAMPTZ,
    last_checked   TIMESTAMPTZ,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    auto_download  SMALLINT NOT NULL DEFAULT 0,
    min_resolution TEXT NOT NULL DEFAULT '',
    max_size_bytes BIGINT NOT NULL DEFAULT 0,
    codec          TEXT NOT NULL DEFAULT ''
);
CREATE INDEX idx_wl_user ON watchlists(user_id);

CREATE TABLE watchlist_seen (
    watchlist_id    BIGINT NOT NULL REFERENCES watchlists(id) ON DELETE CASCADE,
    info_hash       TEXT NOT NULL,
    title           TEXT NOT NULL DEFAULT '',
    magnet          TEXT NOT NULL DEFAULT '',
    seeders         BIGINT NOT NULL DEFAULT 0,
    size            BIGINT NOT NULL DEFAULT 0,
    seen_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    auto_downloaded SMALLINT NOT NULL DEFAULT 0,
    PRIMARY KEY (watchlist_id, info_hash)
);
CREATE INDEX idx_wls_recent ON watchlist_seen(watchlist_id, seen_at DESC);

CREATE TABLE push_subscriptions (
    user_id    BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    endpoint   TEXT NOT NULL UNIQUE,
    p256dh     TEXT NOT NULL,
    auth       TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_push_user ON push_subscriptions(user_id);

CREATE TABLE notifications (
    id         BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    user_id    BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    title      TEXT NOT NULL,
    body       TEXT NOT NULL DEFAULT '',
    magnet     TEXT NOT NULL DEFAULT '',
    read       SMALLINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_notif_user ON notifications(user_id, id DESC);

CREATE TABLE favorite_folders (
    id         BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    user_id    BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    name       TEXT NOT NULL,
    parent_id  BIGINT REFERENCES favorite_folders(id) ON DELETE CASCADE,
    position   BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    hidden     SMALLINT NOT NULL DEFAULT 0,
    -- NULLS NOT DISTINCT so two root folders (parent_id NULL) can't share a
    -- name, matching SQLite's UNIQUE semantics for this store.
    UNIQUE NULLS NOT DISTINCT (user_id, parent_id, name)
);
CREATE INDEX idx_fav_folders_user_parent ON favorite_folders(user_id, parent_id);

CREATE TABLE favorites (
    name         TEXT PRIMARY KEY,
    info_hash    TEXT,
    favorited_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    reason       TEXT NOT NULL DEFAULT 'manual',
    user_id      BIGINT NOT NULL DEFAULT 0 REFERENCES users(id) ON DELETE CASCADE,
    magnet       TEXT NOT NULL DEFAULT '',
    folder_id    BIGINT REFERENCES favorite_folders(id) ON DELETE SET NULL
);
CREATE INDEX idx_fav_hash ON favorites(info_hash);
CREATE INDEX idx_fav_user ON favorites(user_id);

CREATE TABLE hidden_local_paths (
    user_id    BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    mount      TEXT NOT NULL,
    path       TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (user_id, mount, path)
);

CREATE TABLE playlist_items (
    id          BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    playlist_id BIGINT NOT NULL REFERENCES playlists(id) ON DELETE CASCADE,
    position    BIGINT NOT NULL,
    library_id  BIGINT REFERENCES library(id) ON DELETE SET NULL,
    title       TEXT NOT NULL,
    magnet      TEXT NOT NULL,
    info_hash   TEXT NOT NULL DEFAULT '',
    file_index  BIGINT NOT NULL DEFAULT 0,
    added_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_pi_playlist_pos ON playlist_items(playlist_id, position);

CREATE TABLE pending_transfers (
    id         BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    kind       TEXT NOT NULL,
    src        TEXT NOT NULL,
    dst        TEXT NOT NULL,
    payload    TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- Global caches / singletons (no user_id, no FK to users)
-- ---------------------------------------------------------------------------
CREATE TABLE tmdb_match (
    cache_key TEXT PRIMARY KEY,
    payload   TEXT NOT NULL,
    cached_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE trending_snapshot (
    week_key TEXT NOT NULL,
    tmdb_id  BIGINT NOT NULL,
    rank     BIGINT NOT NULL,
    PRIMARY KEY (week_key, tmdb_id)
);

CREATE TABLE benchmark_result (
    slot_id        TEXT PRIMARY KEY,
    provider       TEXT NOT NULL DEFAULT '',
    model          TEXT NOT NULL DEFAULT '',
    accuracy       DOUBLE PRECISION NOT NULL DEFAULT 0,
    avg_latency_ms BIGINT NOT NULL DEFAULT 0,
    composite      DOUBLE PRECISION NOT NULL DEFAULT 0,
    chain_order    BIGINT NOT NULL DEFAULT 0,
    samples        BIGINT NOT NULL DEFAULT 0,
    failure_reason TEXT NOT NULL DEFAULT '',
    incomplete     SMALLINT NOT NULL DEFAULT 0,
    cost_per_1m    DOUBLE PRECISION NOT NULL DEFAULT 0,
    tasks          TEXT NOT NULL DEFAULT '',
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE benchmark_case (
    id     BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    raw    TEXT NOT NULL,
    expect TEXT NOT NULL,
    task   TEXT NOT NULL DEFAULT '',
    origin TEXT NOT NULL DEFAULT ''
);

CREATE TABLE benchmark_setting (
    key   TEXT PRIMARY KEY,
    value DOUBLE PRECISION NOT NULL
);

CREATE TABLE benchmark_history (
    slot_id              TEXT PRIMARY KEY,
    last_outcome         TEXT NOT NULL DEFAULT '',
    last_error           TEXT NOT NULL DEFAULT '',
    last_success_at      TIMESTAMPTZ,
    last_run_at          TIMESTAMPTZ,
    first_failure_at     TIMESTAMPTZ,
    consecutive_failures BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE audio_metadata (
    file_path    TEXT PRIMARY KEY,
    title        TEXT NOT NULL DEFAULT '',
    artist       TEXT NOT NULL DEFAULT '',
    album        TEXT NOT NULL DEFAULT '',
    album_artist TEXT NOT NULL DEFAULT '',
    genre        TEXT NOT NULL DEFAULT '',
    year         BIGINT NOT NULL DEFAULT 0,
    track_number BIGINT NOT NULL DEFAULT 0,
    disc_number  BIGINT NOT NULL DEFAULT 0,
    has_cover    SMALLINT NOT NULL DEFAULT 0,
    last_mod     BIGINT NOT NULL DEFAULT 0,
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_audio_album ON audio_metadata(album);
CREATE INDEX idx_audio_artist ON audio_metadata(artist);

CREATE TABLE seeds (
    info_hash TEXT PRIMARY KEY,
    magnet    TEXT NOT NULL DEFAULT '',
    name      TEXT NOT NULL DEFAULT '',
    added_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE metadata (
    info_hash         TEXT PRIMARY KEY,
    name              TEXT NOT NULL,
    total_size        BIGINT NOT NULL DEFAULT 0,
    files             TEXT NOT NULL DEFAULT '[]',
    primary_file      BIGINT NOT NULL DEFAULT -1,
    cached_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    art_source        TEXT NOT NULL DEFAULT '',
    art_path          TEXT NOT NULL DEFAULT '',
    poster_url        TEXT NOT NULL DEFAULT '',
    tmdb_id           BIGINT NOT NULL DEFAULT 0,
    imdb_id           TEXT NOT NULL DEFAULT '',
    health_seeders    BIGINT NOT NULL DEFAULT -1,
    health_peers      BIGINT NOT NULL DEFAULT -1,
    health_checked_at TIMESTAMPTZ,
    art_checked_at    TIMESTAMPTZ
);

CREATE TABLE vapid_keys (
    id          SMALLINT PRIMARY KEY CHECK (id = 1),
    public_key  TEXT NOT NULL,
    private_key TEXT NOT NULL
);
