#!/bin/bash
# SBOM generation and upload to Dependency-Track via API.
# Runs natively from inside the Gitea Actions working container.

set -e

# DT_API comes from the workflow (secrets.DT_API); no hardcoded default so the
# internal host does not leak.
DT_API="${DT_API}"
DT_USER="${DT_USER}"
DT_PASS="${DT_PASS}"

echo "=== Starting SBOM generation ==="
# Runs native cdxgen via npx (no QEMU or complex docker volume mounts)
FETCH_LICENSE=false npx -y @cyclonedx/cdxgen --spec-version 1.6 -r -t go -t javascript -o bom.json .

if [ ! -s bom.json ]; then
  echo "Error: bom.json is empty or was not generated by cdxgen"
  exit 1
fi

echo "=== SBOM generated successfully (~$(du -h bom.json | cut -f1)) ==="

if [ -z "$DT_API" ] || [ -z "$DT_USER" ] || [ -z "$DT_PASS" ]; then
  echo "Warning: Dependency-Track not configured (DT_API / DT_USER / DT_PASS). Skipping upload."
  exit 0
fi

echo "=== Logging in to Dependency-Track ==="
JWT=$(curl -sk --max-time 20 -X POST "$DT_API/api/v1/user/login" \
  --data-urlencode "username=$DT_USER" \
  --data-urlencode "password=$DT_PASS" || true)

if [ -z "$JWT" ]; then
  echo "Warning: Dependency-Track login failed/empty. Skipping upload."
  exit 0
fi

echo "=== Uploading SBOM to Dependency-Track ==="
printf '{"projectName":"jackui","projectVersion":"main","autoCreate":true,"bom":"%s"}' \
  "$(base64 -w0 bom.json)" > dt-payload.json

HTTP_CODE=$(curl -sk --max-time 60 -o /dev/null -w "%{http_code}" -X PUT "$DT_API/api/v1/bom" \
  -H "Authorization: Bearer $JWT" \
  -H 'Content-Type: application/json' \
  --data-binary @dt-payload.json)

if [ "$HTTP_CODE" = "200" ] || [ "$HTTP_CODE" = "201" ]; then
  echo "=== Upload completed successfully [HTTP $HTTP_CODE] ==="
else
  echo "Warning: SBOM upload to Dependency-Track failed [HTTP $HTTP_CODE]"
fi

# Cleanup
rm -f bom.json dt-payload.json
